<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Features\" />
    <Folder Include="Validators\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\BlogArray.SaaS.Domain\BlogArray.SaaS.Domain.csproj" />
    <ProjectReference Include="..\BlogArray.SaaS.Infrastructure\BlogArray.SaaS.Infrastructure.csproj" />
    <ProjectReference Include="..\BlogArray.SaaS.Web\BlogArray.SaaS.Web.csproj" />
    <ProjectReference Include="..\BlogArray.SaaS.OpenId\BlogArray.SaaS.OpenId.csproj" />
  </ItemGroup>

</Project>
