global using BlogArray.SaaS.Domain.Constants;
global using BlogArray.SaaS.Domain.DTOs;
global using BlogArray.SaaS.Domain.Entities;
global using BlogArray.SaaS.Mvc.Services;
global using BlogArray.SaaS.OpenId;
global using BlogArray.SaaS.Resources.Controllers;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Claims;
