<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\BlogArray.SaaS.Infrastructure\BlogArray.SaaS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Core\BlogArray.SaaS.Web\BlogArray.SaaS.Web.csproj" />
    <ProjectReference Include="..\..\src\Core\BlogArray.SaaS.Domain\BlogArray.SaaS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
